server:
  port: ${SERVER_PORT:8088}

management:
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
      show-details: never

spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all

    consumer:
      group-id: owoke-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "career.flow.owoke.messaging.event"
        isolation.level: read_committed

    listener:
      ack-mode: manual
      concurrency: 3
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secretAccess: ${JWT_ACCESS_SECRET}
  secretRefresh: ${JWT_REFRESH_SECRET}
  expirationAccess: ${JWT_ACCESS_EXPIRATION:3600000}
  expirationRefresh: ${JWT_REFRESH_EXPIRATION:2592000000}

app:
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME:noreply@owoke.local}}
  security:
    refresh-cookie:
      secure: true
      http-only: true
      same-site: Strict
      path: /
      max-age: 30d
    refresh-token:
      key-prefix: "refresh:"
      ttl: 30d
    password-reset:
      rate-limit:
        enabled: true
        key-prefix: "rate:password-reset:"
        cooldown: 5m
