server:
  port: 8088

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xaeshkayt@gmail.com
    password: ltsc dilo hcat vlvu
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5433/owoke_db
    username: owoke
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all

    consumer:
      group-id: owoke-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed

    listener:
      ack-mode: manual
      concurrency: 3
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secretAccess: "access-jhkfs12312kbjgljakljsdfsdkjfsdfhalskdjfhlsdkfhalsd7823124gjhws7878d12344tSSJLHFSDYUFSDALJ123424321adfaHWERNLBASDFG"
  secretRefresh: "refresh-jhkfs12312kbjgljakljsdfsdkjfsdfhalskdjfhlsdkfhalsd7823124gjhws7878d12344tSSJLHFSDYUFSDALJ123424321adfaHWERNLBASDFG"
  expirationAccess: 360000 # 1 час
  expirationRefresh: 259200000 # 1 месяц
